# Generated by Django 4.1.2 on 2022-12-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customsession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="user", max_length=25),
        ),
    ]
