# Generated by Django 4.1.2 on 2022-12-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="commune",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default=None, null=True, upload_to="users_images"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default="+56999999999", max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
