# Generated by Django 4.1.2 on 2022-12-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('serial_number', models.TextField()),
                ('brand', models.CharField(max_length=20)),
                ('is_wifi', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
