# Generated by Django 4.1.2 on 2022-12-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printers", "0003_delete_user_alter_printer_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="printer",
            name="image",
            field=models.ImageField(
                default=None, null=True, upload_to="printer_images"
            ),
        ),
    ]
