# Generated by Django 4.1.2 on 2022-12-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email_alter_user_id"),
        ("printers", "0004_printer_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="printers.printer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
